# Generated by Django 5.2.16 on 2026-07-09 06:22

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True, verbose_name='اسم القسم')),
            ],
            options={
                'verbose_name': 'قسم',
                'verbose_name_plural': 'الأقسام',
            },
        ),
        migrations.CreateModel(
            name='WorkSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('work_start', models.TimeField(default=datetime.time(8, 0), verbose_name='بداية الدوام')),
                ('work_end', models.TimeField(default=datetime.time(17, 0), verbose_name='نهاية الدوام')),
                ('weekend_days', models.JSONField(default=list, verbose_name='أيام الإجازة الأسبوعية')),
            ],
            options={
                'verbose_name': 'جدول العمل',
                'verbose_name_plural': 'جدول العمل',
            },
        ),
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, unique=True, verbose_name='كود الموظف (رقمه على جهاز البصمة)')),
                ('full_name', models.CharField(max_length=200, verbose_name='الاسم بالكامل')),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='المسمى الوظيفي')),
                ('national_id', models.CharField(blank=True, max_length=14, verbose_name='الرقم القومي')),
                ('phone_number', models.CharField(blank=True, max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.TextField(blank=True, verbose_name='العنوان')),
                ('gender', models.CharField(choices=[('male', 'ذكر'), ('female', 'أنثى')], default='male', max_length=10, verbose_name='الجنس')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('hire_date', models.DateField(blank=True, null=True, verbose_name='تاريخ التعيين')),
                ('salary', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='الراتب')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='employee_photos/', verbose_name='صورة الموظف')),
                ('id_front_image', models.ImageField(blank=True, null=True, upload_to='employee_ids/', verbose_name='صورة وجه البطاقة')),
                ('id_back_image', models.ImageField(blank=True, null=True, upload_to='employee_ids/', verbose_name='صورة ظهر البطاقة')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='hr.department', verbose_name='القسم')),
            ],
            options={
                'verbose_name': 'موظف',
                'verbose_name_plural': 'الموظفون',
                'ordering': ['full_name'],
            },
        ),
    ]
