# Generated by Django 5.2.16 on 2026-07-09 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(default='MR.Mekawy Factory ERP', max_length=100, verbose_name='اسم النظام')),
                ('favicon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('icon_192', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('icon_512', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('apple_touch_icon', models.ImageField(blank=True, null=True, upload_to='site/')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات النظام',
                'verbose_name_plural': 'إعدادات النظام',
            },
        ),
    ]
