# Generated by Django 5.2.16 on 2026-08-31 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hr', '0002_sitesettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='is_team_leader',
            field=models.BooleanField(default=False, verbose_name='رئيس فريق'),
        ),
    ]
