# Generated by Django 5.2.16 on 2026-07-09 06:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial_number', models.CharField(max_length=50, unique=True, verbose_name='الرقم التسلسلي')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='اسم الجهاز')),
                ('last_seen', models.DateTimeField(blank=True, null=True, verbose_name='آخر اتصال')),
                ('push_version', models.CharField(blank=True, max_length=20)),
                ('options_raw', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'جهاز بصمة',
                'verbose_name_plural': 'أجهزة البصمة',
            },
        ),
        migrations.CreateModel(
            name='DeviceCommand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('command', models.TextField(verbose_name='الأمر')),
                ('description', models.CharField(blank=True, max_length=200, verbose_name='الوصف')),
                ('status', models.CharField(choices=[('pending', 'قيد الانتظار'), ('sent', 'أُرسل للجهاز'), ('done', 'تم التنفيذ'), ('failed', 'فشل')], default='pending', max_length=10, verbose_name='الحالة')),
                ('return_code', models.CharField(blank=True, max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('finished_at', models.DateTimeField(blank=True, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='commands', to='devices.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'أمر للجهاز',
                'verbose_name_plural': 'أوامر الأجهزة',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='FingerprintTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, verbose_name='كود الموظف')),
                ('finger_id', models.SmallIntegerField(verbose_name='رقم الإصبع')),
                ('template', models.TextField(verbose_name='القالب (base64)')),
                ('valid', models.SmallIntegerField(default=1)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'بصمة',
                'verbose_name_plural': 'البصمات',
                'constraints': [models.UniqueConstraint(fields=('employee_code', 'finger_id'), name='uniq_fp')],
            },
        ),
        migrations.CreateModel(
            name='AttendanceLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('employee_code', models.CharField(max_length=20, verbose_name='كود الموظف')),
                ('timestamp', models.DateTimeField(verbose_name='وقت البصمة')),
                ('punch_state', models.SmallIntegerField(default=0, verbose_name='نوع الحركة')),
                ('verify_type', models.SmallIntegerField(default=1, verbose_name='طريقة التحقق')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='attendance_logs', to='hr.employee', verbose_name='الموظف')),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='devices.device', verbose_name='الجهاز')),
            ],
            options={
                'verbose_name': 'سجل حضور',
                'verbose_name_plural': 'سجلات الحضور',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['employee_code', 'timestamp'], name='devices_att_employe_67951b_idx')],
                'constraints': [models.UniqueConstraint(fields=('device', 'employee_code', 'timestamp'), name='uniq_punch')],
            },
        ),
    ]
