# Generated by Django 5.2.16 on 2026-07-09 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='device',
            name='wipe_requested_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='devicecommand',
            name='delivery_count',
            field=models.PositiveSmallIntegerField(default=0),
        ),
    ]
