# Generated by Django 5.2.16 on 2026-07-09 07:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_device_wipe_requested_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendancelog',
            name='source',
            field=models.CharField(choices=[('device', 'جهاز البصمة'), ('manual', 'إدخال يدوي')], default='device', max_length=10, verbose_name='المصدر'),
        ),
        migrations.AlterField(
            model_name='attendancelog',
            name='device',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attendance_logs', to='devices.device', verbose_name='الجهاز'),
        ),
    ]
