# Generated by Django 5.2.16 on 2026-08-31 19:04

import cutting.models
import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hr', '0003_employee_is_team_leader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Bank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True, verbose_name='كود البنك')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البنك')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
            ],
            options={
                'verbose_name': 'بنك',
                'verbose_name_plural': 'البنوك',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='CuttingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('0.50'), max_digits=5, verbose_name='تسامح القماش %')),
                ('pieces_tolerance_pct', models.DecimalField(decimal_places=2, default=Decimal('2.00'), max_digits=5, verbose_name='تسامح القطع %')),
                ('remnant_waste_threshold_m', models.DecimalField(decimal_places=2, default=Decimal('1.00'), max_digits=6, verbose_name='حد الباقي الهالك (م)')),
                ('notify_emails', models.TextField(blank=True, verbose_name='إيميلات التنبيهات')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'إعدادات القص',
                'verbose_name_plural': 'إعدادات القص',
            },
        ),
        migrations.CreateModel(
            name='GarmentModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=30, unique=True, verbose_name='كود الموديل')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الموديل')),
                ('category', models.CharField(blank=True, choices=[('men', 'رجالي'), ('women', 'حريمي'), ('kids', 'أطفال')], max_length=10, verbose_name='الفئة')),
                ('fit', models.CharField(blank=True, max_length=50, verbose_name='القَصّة')),
                ('image', models.ImageField(blank=True, null=True, upload_to='cutting/models/', verbose_name='صورة الموديل')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'موديل',
                'verbose_name_plural': 'الموديلات',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SizeSet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم الطقم')),
                ('sizes_raw', models.CharField(max_length=200, verbose_name='المقاسات')),
                ('total_pieces', models.PositiveIntegerField(default=0, verbose_name='عدد القطع في الراق')),
                ('is_active', models.BooleanField(default=True, verbose_name='نشط')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'طقم مقاسات',
                'verbose_name_plural': 'أطقم المقاسات',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Lay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='تاريخ البداية')),
                ('end_date', models.DateField(verbose_name='تاريخ النهاية')),
                ('lay_width_cm', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='عرض الفرشة (سم)')),
                ('narrowest_width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض أضيق توب (سم)')),
                ('lay_length_m', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(Decimal('0.01'))], verbose_name='طول الفرشة (م)')),
                ('pieces_per_ply', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='عدد القطع في الراق')),
                ('status', models.CharField(choices=[('open', 'مفتوحة'), ('closed', 'مقفولة'), ('counted', 'مترقّمة'), ('approved', 'معتمدة')], default='open', max_length=10, verbose_name='الحالة')),
                ('entry_mode', models.CharField(choices=[('detailed', 'تفصيلي'), ('quick', 'سريع')], default='detailed', max_length=10, verbose_name='وضع الإدخال')),
                ('is_backfill', models.BooleanField(default=False, verbose_name='إدخال أثري')),
                ('has_splice', models.BooleanField(default=False, verbose_name='فيها وصل')),
                ('sheet_image', models.ImageField(blank=True, null=True, upload_to=cutting.models.lay_image_path, verbose_name='صورة ورقة الدفتر')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('total_plies', models.PositiveIntegerField(default=0, verbose_name='إجمالي الراق')),
                ('theoretical_pieces', models.PositiveIntegerField(default=0, verbose_name='القطع النظرية')),
                ('total_roll_length_m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='إجمالي أطوال الأتواب')),
                ('total_remnant_m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='إجمالي البواقي')),
                ('consumed_m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='القماش المستهلك')),
                ('fabric_shortage_m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=10, verbose_name='عجز القماش')),
                ('expected_metrage', models.DecimalField(decimal_places=4, default=Decimal('0'), max_digits=8, verbose_name='الميتراج المتوقع')),
                ('real_metrage', models.DecimalField(blank=True, decimal_places=4, max_digits=8, null=True, verbose_name='الميتراج الحقيقي')),
                ('deviation_pct', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='انحراف الميتراج %')),
                ('has_shortage', models.BooleanField(default=False, verbose_name='فيها عجز')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True, verbose_name='وقت القفل')),
                ('client_uuid', models.UUIDField(blank=True, null=True, unique=True)),
                ('bank', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lays', to='cutting.bank', verbose_name='البنك')),
                ('closed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='closed_lays', to=settings.AUTH_USER_MODEL, verbose_name='قفلها')),
                ('entered_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='entered_lays', to=settings.AUTH_USER_MODEL, verbose_name='أدخلها')),
                ('garment_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lays', to='cutting.garmentmodel', verbose_name='الموديل')),
                ('team_leader', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='led_lays', to='hr.employee', verbose_name='رئيس الفريق')),
                ('team_members', models.ManyToManyField(blank=True, related_name='member_lays', to='hr.employee', verbose_name='باقي الفريق')),
                ('size_set', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lays', to='cutting.sizeset', verbose_name='طقم المقاسات')),
            ],
            options={
                'verbose_name': 'فرشة',
                'verbose_name_plural': 'الفرشات',
                'ordering': ['-start_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='LayLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_no', models.PositiveIntegerField(verbose_name='رقم السطر')),
                ('roll_ref', models.PositiveIntegerField(blank=True, null=True, verbose_name='رقم التوب في المخزون')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='الخامة')),
                ('lot_no', models.CharField(blank=True, max_length=50, verbose_name='رقم اللوط')),
                ('roll_no', models.CharField(blank=True, max_length=50, verbose_name='رقم التوب')),
                ('barcode', models.CharField(blank=True, max_length=100, verbose_name='الباركود')),
                ('ticket_image', models.ImageField(blank=True, null=True, upload_to=cutting.models.lay_image_path, verbose_name='صورة التيكت')),
                ('ticket_data', models.JSONField(blank=True, default=dict, verbose_name='بيانات التيكت')),
                ('roll_length_m', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='طول التوب (م)')),
                ('plies', models.PositiveIntegerField(verbose_name='الراق')),
                ('remnant_m', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=8, verbose_name='الباقي (م)')),
                ('width_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض التوب (سم)')),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=7, null=True, verbose_name='الوزن الصافي (كجم)')),
                ('shade_note', models.CharField(blank=True, max_length=100, verbose_name='توصيف اللون')),
                ('roll_end_action', models.CharField(choices=[('splice', 'وصل'), ('new_roll', 'توب جديد'), ('stored', 'اتخزن')], default='new_roll', max_length=10, verbose_name='تصرّف نهاية التوب')),
                ('remnant_disposition', models.CharField(blank=True, choices=[('waste', 'هالك'), ('usable', 'صالح')], max_length=10, verbose_name='تصنيف الباقي')),
                ('is_aggregate', models.BooleanField(default=False, verbose_name='سطر مجمّع')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('lay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='cutting.lay')),
            ],
            options={
                'verbose_name': 'سطر توب',
                'verbose_name_plural': 'سطور الأتواب',
                'ordering': ['line_no', 'id'],
            },
        ),
        migrations.CreateModel(
            name='LayOutput',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actual_pieces', models.PositiveIntegerField(verbose_name='القطع السليمة')),
                ('rejected_pieces', models.PositiveIntegerField(default=0, verbose_name='التالف')),
                ('recorded_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True, verbose_name='سبب الفرق')),
                ('lay', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='output', to='cutting.lay')),
                ('recorded_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recorded_outputs', to=settings.AUTH_USER_MODEL, verbose_name='سجّلها')),
            ],
            options={
                'verbose_name': 'قطع فعلية',
                'verbose_name_plural': 'القطع الفعلية',
            },
        ),
        migrations.CreateModel(
            name='LaySizeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('size', models.CharField(max_length=20, verbose_name='المقاس')),
                ('pieces_in_ply', models.PositiveIntegerField(verbose_name='قطع في الراق')),
                ('actual_pieces', models.PositiveIntegerField(blank=True, null=True, verbose_name='القطع الفعلية')),
                ('is_manually_adjusted', models.BooleanField(default=False, verbose_name='اتعدّل يدوي')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('lay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='size_breakdown', to='cutting.lay')),
            ],
            options={
                'verbose_name': 'مقاس في الفرشة',
                'verbose_name_plural': 'مقاسات الفرشة',
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='RemnantLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('length_m', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (م)')),
                ('shade_note', models.CharField(blank=True, max_length=100, verbose_name='توصيف اللون')),
                ('lot_no', models.CharField(blank=True, max_length=50, verbose_name='رقم اللوط')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='الخامة')),
                ('disposition', models.CharField(choices=[('waste', 'هالك'), ('usable', 'صالح')], max_length=10, verbose_name='التصنيف')),
                ('logged_at', models.DateTimeField(auto_now_add=True)),
                ('lay_line', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='remnant_log', to='cutting.layline')),
            ],
            options={
                'verbose_name': 'باقي مسجّل',
                'verbose_name_plural': 'سجل البواقي',
                'ordering': ['-logged_at'],
            },
        ),
        migrations.AddField(
            model_name='garmentmodel',
            name='default_size_set',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='models', to='cutting.sizeset', verbose_name='طقم المقاسات المعتاد'),
        ),
        migrations.CreateModel(
            name='LayAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('at', models.DateTimeField(auto_now_add=True)),
                ('action', models.CharField(max_length=30, verbose_name='الحدث')),
                ('field', models.CharField(blank=True, max_length=50, verbose_name='الحقل')),
                ('old_value', models.TextField(blank=True, verbose_name='القيمة القديمة')),
                ('new_value', models.TextField(blank=True, verbose_name='القيمة الجديدة')),
                ('reason', models.TextField(blank=True, verbose_name='السبب')),
                ('lay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_entries', to='cutting.lay')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='lay_audit_entries', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سجل نشاط',
                'verbose_name_plural': 'سجل النشاط',
                'ordering': ['-at', '-id'],
                'indexes': [models.Index(fields=['lay', 'at'], name='audit_lay_at_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='layline',
            index=models.Index(fields=['article'], name='line_article_idx'),
        ),
        migrations.AddIndex(
            model_name='layline',
            index=models.Index(fields=['lot_no'], name='line_lot_idx'),
        ),
        migrations.AddConstraint(
            model_name='layline',
            constraint=models.UniqueConstraint(fields=('lay', 'line_no'), name='uniq_lay_line_no'),
        ),
        migrations.AddConstraint(
            model_name='layline',
            constraint=models.CheckConstraint(condition=models.Q(('plies__gt', 0)), name='line_plies_positive'),
        ),
        migrations.AddConstraint(
            model_name='layline',
            constraint=models.CheckConstraint(condition=models.Q(('roll_length_m__gt', 0)), name='line_length_positive'),
        ),
        migrations.AddIndex(
            model_name='laysizebreakdown',
            index=models.Index(fields=['size'], name='breakdown_size_idx'),
        ),
        migrations.AddConstraint(
            model_name='laysizebreakdown',
            constraint=models.UniqueConstraint(fields=('lay', 'size'), name='uniq_lay_size'),
        ),
        migrations.AddIndex(
            model_name='remnantlog',
            index=models.Index(fields=['disposition'], name='remnant_disposition_idx'),
        ),
        migrations.AddIndex(
            model_name='remnantlog',
            index=models.Index(fields=['article'], name='remnant_article_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['start_date', 'end_date'], name='lay_period_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['status', 'end_date'], name='lay_status_end_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['team_leader', 'start_date'], name='lay_leader_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['bank', 'start_date'], name='lay_bank_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['garment_model', 'start_date'], name='lay_model_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['has_shortage'], name='lay_shortage_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['is_backfill'], name='lay_backfill_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['deviation_pct'], name='lay_deviation_idx'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['real_metrage'], name='lay_real_metrage_idx'),
        ),
        migrations.AddConstraint(
            model_name='lay',
            constraint=models.CheckConstraint(condition=models.Q(('end_date__gte', models.F('start_date'))), name='lay_end_after_start'),
        ),
    ]
