# Generated by Django 5.2.16 on 2026-07-11 09:12

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CuttingOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='كود القصة')),
                ('model_name', models.CharField(max_length=200, verbose_name='اسم الموديل')),
                ('color', models.CharField(blank=True, max_length=100, verbose_name='اللون')),
                ('production_order_no', models.CharField(blank=True, max_length=100, verbose_name='رقم أمر الإنتاج')),
                ('cutting_date', models.DateField(default=django.utils.timezone.localdate, verbose_name='تاريخ القص')),
                ('worksheet_photo', models.ImageField(blank=True, null=True, upload_to='cutting_worksheets/', verbose_name='صورة ورقة القصة')),
                ('quick_total_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='إجمالي الأمتار (إدخال سريع)')),
                ('has_shortage', models.BooleanField(default=False, verbose_name='يوجد عجز')),
                ('shortage_quantity', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='كمية العجز')),
                ('shortage_reason', models.CharField(blank=True, max_length=200, verbose_name='سبب العجز')),
                ('shortage_notes', models.TextField(blank=True, verbose_name='ملاحظات العجز')),
                ('notes', models.TextField(blank=True, verbose_name='ملاحظات')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cuttings', to=settings.AUTH_USER_MODEL, verbose_name='موظف القص')),
            ],
            options={
                'verbose_name': 'قصة',
                'verbose_name_plural': 'القصات',
                'ordering': ['-cutting_date', '-id'],
            },
        ),
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fabric_width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='عرض الفرشة (سم)')),
                ('marker_length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='طول الفرشة (متر)')),
                ('min_top_length', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='أقل توب (متر)')),
                ('pieces_per_lay', models.PositiveIntegerField(verbose_name='عدد القطع في الراقة')),
                ('layers_count', models.PositiveIntegerField(blank=True, null=True, verbose_name='عدد الطبقات')),
                ('lays_count', models.PositiveIntegerField(verbose_name='عدد الراقات')),
                ('cutting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='markers', to='cutting.cuttingorder', verbose_name='القصة')),
            ],
            options={
                'verbose_name': 'فرشة',
                'verbose_name_plural': 'الفرشات',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='FabricRoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roll_number', models.CharField(blank=True, max_length=100, verbose_name='رقم التوب')),
                ('lot_number', models.CharField(blank=True, max_length=100, verbose_name='رقم اللوط')),
                ('article_name', models.CharField(blank=True, max_length=200, verbose_name='اسم الخامة')),
                ('color', models.CharField(max_length=100, verbose_name='اللون')),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='العرض (سم)')),
                ('length', models.DecimalField(decimal_places=2, max_digits=8, verbose_name='الطول (متر)')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='الوزن (كجم)')),
                ('grade', models.CharField(blank=True, max_length=50, verbose_name='الدرجة')),
                ('lays_used', models.PositiveIntegerField(default=0, verbose_name='الراق المستخدم')),
                ('actual_remaining', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name='الباقي الفعلي (متر)')),
                ('status', models.CharField(choices=[('open', 'قيد الاستخدام'), ('finished', 'خلص'), ('remnant', 'به باقي')], default='open', max_length=20, verbose_name='الحالة')),
                ('label_photo', models.ImageField(blank=True, null=True, upload_to='roll_labels/', verbose_name='صورة الليبل')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cutting', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rolls', to='cutting.cuttingorder', verbose_name='القصة')),
                ('marker', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='rolls', to='cutting.marker', verbose_name='الفرشة')),
            ],
            options={
                'verbose_name': 'توب',
                'verbose_name_plural': 'الأتواب',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('roll_number', ''), _negated=True), fields=('cutting', 'roll_number'), name='uniq_rollno_per_cutting')],
            },
        ),
    ]
