# Generated by Django 5.2.16 on 2026-07-11 10:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MarkerSize',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=30, verbose_name='المقاس')),
                ('ratio', models.PositiveIntegerField(default=1, verbose_name='عدد القطع في الراقة')),
                ('marker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sizes', to='cutting.marker', verbose_name='الفرشة')),
            ],
            options={
                'verbose_name': 'مقاس',
                'verbose_name_plural': 'المقاسات',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('marker', 'label'), name='uniq_size_per_marker')],
            },
        ),
    ]
