# Generated by Django 5.2.16 on 2026-08-31 19:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0001_initial'),
        ('hr', '0003_employee_is_team_leader'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lay',
            name='has_length_mismatch',
            field=models.BooleanField(default=False, verbose_name='فيها فرق في الأطوال'),
        ),
        migrations.AddIndex(
            model_name='lay',
            index=models.Index(fields=['has_length_mismatch'], name='lay_length_mismatch_idx'),
        ),
    ]
