# Generated by Django 5.2.16 on 2026-08-31 21:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0002_lay_has_length_mismatch_lay_lay_length_mismatch_idx'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SavedFilter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='اسم البحث')),
                ('query', models.TextField(blank=True, verbose_name='نص البحث')),
                ('params', models.TextField(blank=True, verbose_name='باقي الفلاتر')),
                ('is_shared', models.BooleanField(default=False, verbose_name='مشترك')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cutting_saved_filters', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'بحث محفوظ',
                'verbose_name_plural': 'البحثات المحفوظة',
                'ordering': ['name'],
                'constraints': [models.UniqueConstraint(fields=('owner', 'name'), name='uniq_saved_filter_name')],
            },
        ),
    ]
