# Generated by Django 5.2.16 on 2026-09-01 12:08

"""Drop the per-roll ticket photo and its JSON blob.

SRS 4.3.1 asked for a picture of every roll's ticket so the data could be read
out of it later. Nobody on the floor is going to photograph a ticket per roll,
and a field that is never filled is worse than no field: it sits in front of
the supervisor implying he forgot something.

The notebook page photo on the lay stays. That one really does get taken.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0009_lay_code_unique'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='layline',
            name='ticket_data',
        ),
        migrations.RemoveField(
            model_name='layline',
            name='ticket_image',
        ),
    ]
