# Generated by Django 5.2.16 on 2026-09-01 12:57

"""Drop V1 and the three fields nothing filled.

V1 compared the lay width against the narrowest roll on the table. It needed a
width typed for every single roll, and the man spreading the fabric already
knows which roll is narrowest — he is holding it. The rule could not tell him
anything he did not already know, in exchange for a field on every line, so
both go.

`net_weight_kg` and `Lay.narrowest_width_cm` go with them: neither fed a
calculation, a report, or a screen.

`Lay.lay_width_cm` stays — that one is typed on the new-lay screen and is in
the notebook.
"""
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0010_drop_ticket_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lay',
            name='narrowest_width_cm',
        ),
        migrations.RemoveField(
            model_name='layline',
            name='net_weight_kg',
        ),
        migrations.RemoveField(
            model_name='layline',
            name='width_cm',
        ),
    ]
