# Generated by Django 5.2.16 on 2026-09-01 15:58

import django.db.models.deletion
"""Size sets become reusable presets, grouped by section.

The same runs come up again and again — "رجالي: 30 32 34 36 38" — and typing
them size by size every time is the slowest part of the screen. A preset is a
SizeSet somebody saved on purpose; entering sizes by hand on a lay also lands a
SizeSet row, because that is how the breakdown gets its snapshot, and those
must not show up in the picker beside the real ones.

Attaching a section lets the presets for the model's own section sort first.
"""
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0011_drop_v1_width_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='sizeset',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='size_sets', to='cutting.category', verbose_name='القسم'),
        ),
        migrations.AddField(
            model_name='sizeset',
            name='is_preset',
            field=models.BooleanField(default=False, verbose_name='طقم محفوظ'),
        ),
        migrations.AddIndex(
            model_name='sizeset',
            index=models.Index(fields=['is_preset', 'category'], name='sizeset_preset_idx'),
        ),
    ]
