# Generated by Django 5.2.16 on 2026-09-01 16:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cutting', '0012_size_set_presets'),
    ]

    operations = [
        migrations.CreateModel(
            name='LayShadeBreakdown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shade', models.CharField(max_length=100, verbose_name='اللون')),
                ('plies', models.PositiveIntegerField(verbose_name='الراق')),
                ('is_manual', models.BooleanField(default=False, verbose_name='مُدخَل يدوي')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='الترتيب')),
                ('lay', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shade_breakdown', to='cutting.lay')),
            ],
            options={
                'verbose_name': 'لون في القصة',
                'verbose_name_plural': 'ألوان القصة',
                'ordering': ['order', 'id'],
                'indexes': [models.Index(fields=['shade'], name='shade_name_idx')],
                'constraints': [models.UniqueConstraint(fields=('lay', 'shade'), name='uniq_lay_shade')],
            },
        ),
    ]
